inventory:
  plugin: nornir.plugins.inventory.ansible.AnsibleInventory
  options:
    hostsfile: "ansible-hosts"
  transform_function: exercise2a.transform_ansible_inventory

logging:
  enabled: False
